### ISSUE TITLE
🐛 获取整个收藏夹所有文件的 metadata 时进行了错误的重命名

### ISSUE THREAD

**Issue by XDcedar** [yutto-dev/yutto#457]
### 问题简述

对收藏夹进行操作时，如果收藏夹中不同视频的分P（注意与“多P投稿视频”做区分）拥有相同的名字，保存 metadata 时会出现类似这样的提示：`WARN  文件名重复，已重命名为 序列 (1)`
然而根本不需要重命名，因为它们会被保存在不同的路径下。

### 复现方式

1. 新建 test 收藏夹
2. 收藏如下视频：[BV1Xh411Y7Gn](https://www.bilibili.com/video/BV1Xh411Y7Gn/)、[BV1sY411G78y](https://www.bilibili.com/video/BV1sY411G78y/)、[BV1Do4y1R7cA](https://www.bilibili.com/video/BV1Do4y1R7cA/)
3. 执行 `yutto --batch --config "/path/to/yutto.config" "your test favlist"`
4. 出现警告 `WARN  文件名重复，已重命名为 序列 (1)`

使用的配置文件：
```toml
[basic]
# 设置 SESSDATA
sessdata = "your sessdata"
# 设置大会员严格校验
vip_strict = false
# 设置登录严格校验
login_strict = true
# 无颜色，默认为false
no_color = true
# 无进度条，默认为false
no_progress = true
# 指定媒体元数据值的格式（首演日期，即投稿日期）
metadata_format_premiered = "%Y-%m-%d %H:%M:%S"

[resource]
# 只下载 metadata
require_video = false
require_audio = false
require_danmaku = false
require_metadata = true
save_cover = false

[danmaku]

[batch]
```

### 环境信息

-  OS: Windows11
-  Python: 3.11
-  yutto: 2.0.1
-  FFmpeg: -
-  如果是显示相关问题: no
-  Others: -

### 额外信息

也许跟 #281 的修改有关

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式
