### ISSUE TITLE
🐛 在配置文件中设置不下载封面，但并不生效

### ISSUE THREAD

**Issue by XDcedar** [yutto-dev/yutto#458]
### 问题简述

把配置文件的 `[resource]` 全设为否，只下载 metadata，结果封面还是被下载下来了。

感觉是跟这行代码有关，封面会在不下载视频和音频的情况下自动下载，但我不确定。
https://github.com/yutto-dev/yutto/blob/63153cae3f3d505dc38cfd894479f63782485b3d/src/yutto/processor/downloader.py#L361

另外我以为获取 metadata 的过程并不涉及封面下载，但看起来好像是先下了再删掉？不太明白为何要这么设计。

### 复现方式

配置文件
```toml
[basic]
# 设置 SESSDATA
sessdata = "your sessdata"
# 设置大会员严格校验
vip_strict = false
# 设置登录严格校验
login_strict = true
# 无颜色，默认为false
no_color = true
# 无进度条，默认为false
no_progress = true
# 指定媒体元数据值的格式（首演日期，即投稿日期）
metadata_format_premiered = "%Y-%m-%d %H:%M:%S"

[resource]
# 只下载 metadata
require_video = false
require_audio = false
require_danmaku = false
require_metadata = true
save_cover = false  # <-- 这里设置了不下载封面

[danmaku]

[batch]
```

### 环境信息

- OS: Windows11
- Python: 3.11
- yutto: 2.0.1
- FFmpeg: -
- 如果是显示相关问题: no
- Others: -

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
>  `if options["save_cover"] or (not will_download_video and not will_download_audio): `

@MrXnneHang 这里是为啥来着？:joy:

**Comment by MrXnneHang** [comment]
首先 `cover_path.write_bytes(cover_data)` 保存的封面是用于合并音视频后作为封面的 =-=。

我在后面加了 `if options["save_cover"] or (not will_download_video and not will_download_audio): ` 是确定用户选择保留封面的时候，就显示一个 info。

`not will_download_video and not will_download_audio`  是考虑了 `--cover-only` 的情况。之所以看起来比较反人类，是因为 `--cover-only`设计比较反人类，它会先把音视频下载下来，然后再把音视频删掉只留 cover。

`cover_data is not None and (not will_download_video and not will_download_audio)` 代表的是在 `--cover-only` 的时候打印 info.

不过这里有个坑，就是当`not require_audio and not require_video` 的时候，封面是不会被下载的 =-=。

它会蹦到这里
[https://github.com/yutto-dev/yutto/blob/63153cae3f3d505dc38cfd894479f63782485b3d/src/yutto/processor/downloader.py#L373](https://github.com/yutto-dev/yutto/blob/63153cae3f3d505dc38cfd894479f63782485b3d/src/yutto/processor/downloader.py#L373)


会存在这个问题:

```shell
xnne@xnne-PC:~/code/yutto$ uv run yutto https://www.bilibili.com/video/BV1vZ4y1M7mQ/?vd_source=d7601f0fc447d708fff71aa75186ea10 --metadata-only --save-cover
 INFO  未提供 SESSDATA，无法下载高清视频、字幕等资源哦～
 WARN  没有下载封面的情况下是无法保留封面的哦～
```

当没有捆绑音视频当中一个的时候，封面不会被下载。

**Comment by MrXnneHang** [comment]
比较好的解法是优化`--cover-only`的实现。

我先复现一下 issue 看看，因为从 cli 看起来，这种情况不应该存在。

**Comment by MrXnneHang** [comment]
问题出在这里:

[https://github.com/yutto-dev/yutto/blob/a1bd93c94de3ef44cd0a2554c0734219f627a2aa/src/yutto/cli/settings.py#L69](https://github.com/yutto-dev/yutto/blob/a1bd93c94de3ef44cd0a2554c0734219f627a2aa/src/yutto/cli/settings.py#L69)

**Comment by XDcedar** [comment]
啊？怎么有两个跟cover相关的配置项？

**Comment by MrXnneHang** [comment]
emmmm ，因为有两个形式的 cover .

一个是合并到 mp4 的封面，一个是单独保存的 jpg.

不过这么做确实有点难受，因为 resource 的 select 和 deselect 会让这俩互斥。

**Comment by XDcedar** [comment]
难怪多P视频每个分P都会下好多份重复的封面图 :joy:
所以只使用 `require_cover` 不使用 `save_cover` 就可以了吧？

感觉如果想加合并视频的配置，单独拆成子配置比较好，比如配置文件里加上 `[merge]`，先下载下来再处理
```toml
[resource]
# 只下载 metadata
require_video = false
require_audio = false
require_danmaku = false
require_metadata = true
require_cover = true

[merge]  # 加在这里
merge_cover_into_video = true  # 如果 resource.require_cover 为 false 直接报错
```
反正是配置文件，多写点也无所谓
