### ISSUE TITLE
🐛 require_cover 无效，封面下载下来后又被自动删除

### ISSUE THREAD

**Issue by XDcedar** [yutto-dev/yutto#471]
### 问题简述

不会报错，但添加 `require_cover = true` 不会下载封面。
打开文件夹会发现封面被下载下来后立刻就被删除了。

### 复现方式

随便找了个有分P的视频
`yutto --batch --config "D:\CedarWorkspace\CedarCode\yutto-metadata-download\yutto.config.toml" "https://www.bilibili.com/video/BV1Hi4y187i8/"`

```toml
[basic]
# 设置 SESSDATA
sessdata = "your sessdata"
# 设置大会员严格校验
vip_strict = false
# 设置登录严格校验
login_strict = true
# 无颜色，默认为false
no_color = true
# 无进度条，默认为false
no_progress = true
# 指定媒体元数据值的格式（首演日期，即投稿日期）
metadata_format_premiered = "%Y-%m-%d %H:%M:%S"
# 下载间隔，默认为 0 秒
download_interval = 1

[resource]
# 下载 metadata、章节和封面
require_video = false
require_audio = false # 试过改成 true，一样不行
require_subtitle = false
require_danmaku = false
require_metadata = true
require_chapter_info = true
require_cover = true

[danmaku]

[batch]
```

### 环境信息

-  OS: Windows11
-  Python: 3.11
-  yutto: 2.0.2
-  FFmpeg: -
-  如果是显示相关问题: no
-  Others: -

### 额外信息

参见 #458 

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式
