### ISSUE TITLE
✨ 希望能根据收藏时间筛选收藏的视频

### ISSUE THREAD

**Issue by XDcedar** [yutto-dev/yutto#478]
### 特性描述

在配置文件中添加类似这样的选项
```toml
[batch]
filter_favlist_added_start_time = 2025-01-01
filter_favlist_added_end_time = 2025-01-02
```
能根据这两个选项筛选出需要下载的视频

### 建议解决方案

直接在 `utils/filter.py` 里加上？但这个 `Filter` 是不是要改个名？

### 额外信息

俺其实读了一下代码，可以尝试PR，但俺代码能力未必够，只能说试着改改（主要是不知怎么写测试去保证准确）

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式
